CREATE TABLE token_transfers (
  hash VARCHAR PRIMARY KEY UNIQUE NOT NULL, 
  block BIGINT NOT NULL,
  token VARCHAR NOT NULL,
  from_address VARCHAR NOT NULL,
  to_address VARCHAR NOT NULL,
  value VARCHAR NOT NULL,
  log_index BIGINT NOT NULL,
  chain VARCHAR NOT NULL
)